groups:
  - name: app
    jobs:
      - test-app
      - build-app-dev
  - name: all
    jobs:
      - test-all
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mbellgb/ucl-assistant
      branch: master
  - name: repo-app
    type: git
    source:
      uri: https://github.com/mbellgb/ucl-assistant
      branch: master
      paths: ["app/**/*"]
jobs:
  - name: test-app
    public: true
    plan:
      - get: repo-app
        trigger: true
      - task: test
        file: repo-app/ci/tasks/test.yml
        params:
          APP_NAME: app
        input_mapping: { repo: repo-app }
  - name: test-all
    public: true
    plan:
      - get: repo
        trigger: true
      - task: test
        file: repo/ci/tasks/test-all.yml
        input_mapping: { repo: repo }
jobs:
  - name: build-app-dev
    public: false
    plan:
    - get: repo-app
      passed: [test-app]
      trigger: true
    - task: copy-app-json
      config:
        image_resource:
          type: docker-iamge
          source: {repository: busybox}
        params:
          APP_JSON: ((app-json))
        inputs:
          - name: repo-app
        outputs:
          - name: repo-app
        run:
          dir: repo-app/app
          path: sh
          args: [
            "-c"
            "app.json <<< $APP_JSON"
          ]
    - task: exp-build-android
      image_resource:
        type: docker-image
        source: {repository: "mbellgb/expo"}
      params:
        EXP_USERNAME: ((exp-username))
        EXP_PASSWORD: ((exp-password))
      inputs:
        - name: repo-app
      run:
        dir: repo-app/app
        args: [
          "build:android",

        ]
